services:
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: mememuseum
    env_file:
      - .env
    volumes:
      - image_data:/data/uploads
    depends_on:
      postgres:
        condition: service_healthy
  
  flyway:
    image: flyway/flyway:latest
    container_name: flyway_tecweb
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      FLYWAY_URL: ${POSTGRES_URL}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./migrations:/flyway/sql/migrations
    restart: "no"
    command: migrate
  
  postgres:
    image: postgres:alpine
    container_name: postgres_tecweb
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

  image_data:
